apiVersion: v1
kind: Pod
metadata:
  name: apache
spec:
  containers:
    - name: apache
      image: httpd
      env:
      - name: CONTENT
        valueFrom:
          configMapKeyRef:
            name: q5
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: credentials
            value: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: credentials
            value: password
