apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: qq3
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
