apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  namespace: qq3
  labels:
    k8s-app: nginx
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: ngix
        image: nginx
