apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: qq3
spec:
  containers:
  - name: redis
    image: redis
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "0.5"
        memory: "500Mi"
